//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vluchten_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passagier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Passagier()
        {
            this.Reserveringen = new HashSet<Reservering>();
        }
    
        public int id { get; set; }
        public string emailadres { get; set; }
        public string voornaam { get; set; }
        public string achternaam { get; set; }
        public string telefoonnummer { get; set; }
        public System.DateTime geboortedatum { get; set; }
        public string nationaliteit { get; set; }
        public string postcode { get; set; }
        public string plaats { get; set; }
        public string straat { get; set; }
        public string huisnummer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservering> Reserveringen { get; set; }
    }
}
