//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vluchten_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserveringvlucht
    {
        public int id { get; set; }
        public int reserveringId { get; set; }
        public string vluchtId { get; set; }
    
        public virtual Reservering Reservering { get; set; }
        public virtual Vlucht Vlucht { get; set; }
    }
}
