//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vluchten_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservering
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservering()
        {
            this.Reserveringvluchten = new HashSet<Reserveringvlucht>();
        }
    
        public int id { get; set; }
        public string boekingscode { get; set; }
        public int passagierId { get; set; }
        public int klasseId { get; set; }
        public System.DateTime boekingsdatum { get; set; }
        public string betaalmethode { get; set; }
        public string boekingsstatus { get; set; }
    
        public virtual Klasse Klasse { get; set; }
        public virtual Passagier Passagier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserveringvlucht> Reserveringvluchten { get; set; }
    }
}
