//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vluchten_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vlucht
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vlucht()
        {
            this.Reserveringvluchten = new HashSet<Reserveringvlucht>();
        }
    
        public string id { get; set; }
        public int toestelId { get; set; }
        public int bestemming { get; set; }
        public int vertrek { get; set; }
        public System.DateTime vertrektijd { get; set; }
        public System.DateTime aankomsttijd { get; set; }
        public decimal vluchtprijs { get; set; }
        public System.DateTime datum { get; set; }
    
        public virtual Luchthaven Luchthaven { get; set; }
        public virtual Luchthaven Luchthaven1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserveringvlucht> Reserveringvluchten { get; set; }
    }
}
